name: Tests-Windows

on: [push]

jobs:
  tests-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        python-version: '3.11'
    - name: Install dependencies
      run: |
        conda env update --file env-dev.yml --name base
        conda activate base
    - name: build Eelbrain
      run: |
        conda activate base
        pip install -e .
    - name: Test with pytest
      run: |
        conda activate base
        python -m pytest --version
        python -m pytest eelbrain --no-gui
